In [1]:
import pandas as pd

In [2]:
places_cleaned = pd.read_csv('places_cleaned.csv')
place_recording_binary = pd.read_csv('place_recording_binary.csv')
place_work_binary = pd.read_csv('place_work_binary.csv')

C:\Users\Vashist\AppData\Local\Temp\ipykernel_17028\2410653019.py:1: DtypeWarning: Columns (7,14,15,16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  places_cleaned = pd.read_csv('places_cleaned.csv')

In [3]:
merged_df = places_cleaned.merge(place_recording_binary, left_on='id', right_on='place_id', how='left')
merged_df = merged_df.merge(place_work_binary, left_on='id', right_on='place_id', how='left')

In [4]:
merged_df

,Unnamed: 0_x,id,type,type-id,score,name,address,coordinates,area,life-span,...,premiere,written at,composed at,lyrics written at,libretto written at,revised at,translated at,arranged at_y,commissioned,dedication
0,0,f9a1fd95-4c6d-43a6-bb31-4ee8d5a44a8b,Studio,05fa6a09-ff92-3d34-bdbb-5141d3c24f38,100,Columbia (CBS) Studio ‘B’,"49 East 52nd Street, Manhattan, New York City","{'latitude': '40.759164', 'longitude': '-73.97...","{'id': '74e50e58-5deb-4b99-93a2-decbb365c07f',...",{'ended': None},...,0,0,0,0,0,0,0,0,0,0
1,1,42e9fa7c-a981-44f9-943c-bf39a8c6ce8d,Venue,cd92781a-a73f-30e8-a430-55d7521338db,100,New Theatre Oxford,"George St, Oxford OX1 2AG","{'latitude': '51.753951', 'longitude': '-1.260...","{'id': '33587495-c775-4483-b819-931c4cf438cd',...",{'ended': None},...,0,0,0,0,0,0,0,0,0,0
2,2,34e7351d-715d-4b20-a5d6-3c0bd717eb1d,Religious building,a120ca4a-69e9-3c0e-bc09-21cae26eb621,100,Santuario della Beata Vergine di Ariadello,NaN,"{'latitude': '45.316087', 'longitude': '9.8651...","{'id': '686e7b1e-613f-419c-bcc1-1e84df36586a',...","{'begin': '1666', 'ended': None}",...,0,0,0,0,0,0,0,0,0,0
3,3,0ad32768-514b-410f-9d5a-40ebb0c3373c,Studio,05fa6a09-ff92-3d34-bdbb-5141d3c24f38,100,ROKU-st,〒106-0032 東京都港区六本木 3-4-24 六本木足立ビルB1F,"{'latitude': '35.664122', 'longitude': '139.72...","{'id': 'd9fd27ac-b36f-492b-b598-039ee0dd08c1',...",{'ended': None},...,0,0,0,0,0,0,0,0,0,0
4,4,0b050655-48da-4be7-b5de-7a3ee7370b9e,Venue,cd92781a-a73f-30e8-a430-55d7521338db,100,Rätschenmühle,"Schlachthausstraße 22, 73312 Geislingen/Steige","{'latitude': '48.627518', 'longitude': '9.8256...","{'id': '4518c94c-b6ee-40d0-b4b6-fc27b06fa011',...",{'ended': None},...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69658,69658,8f544074-fecb-49af-a761-c6e8b35d8486,Studio,05fa6a09-ff92-3d34-bdbb-5141d3c24f38,100,Full and Empty,NaN,NaN,"{'id': '29a709d8-0320-493e-8d0c-f2c386662b7f',...",{'ended': None},...,0,0,0,0,0,0,0,0,0,0
69659,69659,90f30083-88db-49a7-8ec1-06d9ca2aa065,Venue,cd92781a-a73f-30e8-a430-55d7521338db,100,Plama,NaN,NaN,"{'id': '70cd6f66-9881-4105-8096-8721a1887aad',...",{'ended': None},...,0,0,0,0,0,0,0,0,0,0
69660,69660,6b94062e-78a3-46e8-b861-d801dfe27376,Studio,05fa6a09-ff92-3d34-bdbb-5141d3c24f38,100,Studio Toupie,NaN,NaN,NaN,{'ended': None},...,0,0,0,0,0,0,0,0,0,0
69661,69661,f7362574-05ac-4c21-8196-26a09d6e5fe7,Studio,05fa6a09-ff92-3d34-bdbb-5141d3c24f38,100,FatCat Studio,NaN,NaN,NaN,{'ended': None},...,0,0,0,0,0,0,0,0,0,0
69662,69662,6bd7adb1-b8dd-4ee5-bbe8-788444556350,Studio,05fa6a09-ff92-3d34-bdbb-5141d3c24f38,100,Farida Studio,"FARIDA STUDIO, Lintel 17, 27711 Osterholz-Scha...",NaN,"{'id': '9c607066-ceb6-4a78-a614-4c14a2b3ec35',...",{'ended': None},...,0,0,0,0,0,0,0,0,0,0

In [5]:
merged_df.drop(columns = ['place_id_x', 'place_id_y'], inplace=True)

In [7]:
merged_df.columns

Index(['Unnamed: 0_x', 'id', 'type', 'type-id', 'score', 'name', 'address',
       'coordinates', 'area', 'life-span', 'disambiguation', 'aliases',
       'latitude', 'longitude', 'city', 'state', 'county', 'country',
       'lifespan_years', 'Unnamed: 0_y', 'arranged at_x', 'engineered at',
       'recorded at', 'mixed at', 'edited at', 'remixed at', 'produced at',
       'video shot at', 'Unnamed: 0', 'premiere', 'written at', 'composed at',
       'lyrics written at', 'libretto written at', 'revised at',
       'translated at', 'arranged at_y', 'commissioned', 'dedication'],
      dtype='object')

In [12]:
merged_df = merged_df.drop(columns=[col for col in merged_df.columns if "Unnamed: 0" in col], errors='ignore')

In [13]:
merged_df

,id,type,type-id,score,name,address,coordinates,area,life-span,disambiguation,...,premiere,written at,composed at,lyrics written at,libretto written at,revised at,translated at,arranged at_y,commissioned,dedication
0,f9a1fd95-4c6d-43a6-bb31-4ee8d5a44a8b,Studio,05fa6a09-ff92-3d34-bdbb-5141d3c24f38,100,Columbia (CBS) Studio ‘B’,"49 East 52nd Street, Manhattan, New York City","{'latitude': '40.759164', 'longitude': '-73.97...","{'id': '74e50e58-5deb-4b99-93a2-decbb365c07f',...",{'ended': None},NaN,...,0,0,0,0,0,0,0,0,0,0
1,42e9fa7c-a981-44f9-943c-bf39a8c6ce8d,Venue,cd92781a-a73f-30e8-a430-55d7521338db,100,New Theatre Oxford,"George St, Oxford OX1 2AG","{'latitude': '51.753951', 'longitude': '-1.260...","{'id': '33587495-c775-4483-b819-931c4cf438cd',...",{'ended': None},NaN,...,0,0,0,0,0,0,0,0,0,0
2,34e7351d-715d-4b20-a5d6-3c0bd717eb1d,Religious building,a120ca4a-69e9-3c0e-bc09-21cae26eb621,100,Santuario della Beata Vergine di Ariadello,NaN,"{'latitude': '45.316087', 'longitude': '9.8651...","{'id': '686e7b1e-613f-419c-bcc1-1e84df36586a',...","{'begin': '1666', 'ended': None}",NaN,...,0,0,0,0,0,0,0,0,0,0
3,0ad32768-514b-410f-9d5a-40ebb0c3373c,Studio,05fa6a09-ff92-3d34-bdbb-5141d3c24f38,100,ROKU-st,〒106-0032 東京都港区六本木 3-4-24 六本木足立ビルB1F,"{'latitude': '35.664122', 'longitude': '139.72...","{'id': 'd9fd27ac-b36f-492b-b598-039ee0dd08c1',...",{'ended': None},NaN,...,0,0,0,0,0,0,0,0,0,0
4,0b050655-48da-4be7-b5de-7a3ee7370b9e,Venue,cd92781a-a73f-30e8-a430-55d7521338db,100,Rätschenmühle,"Schlachthausstraße 22, 73312 Geislingen/Steige","{'latitude': '48.627518', 'longitude': '9.8256...","{'id': '4518c94c-b6ee-40d0-b4b6-fc27b06fa011',...",{'ended': None},NaN,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69658,8f544074-fecb-49af-a761-c6e8b35d8486,Studio,05fa6a09-ff92-3d34-bdbb-5141d3c24f38,100,Full and Empty,NaN,NaN,"{'id': '29a709d8-0320-493e-8d0c-f2c386662b7f',...",{'ended': None},NaN,...,0,0,0,0,0,0,0,0,0,0
69659,90f30083-88db-49a7-8ec1-06d9ca2aa065,Venue,cd92781a-a73f-30e8-a430-55d7521338db,100,Plama,NaN,NaN,"{'id': '70cd6f66-9881-4105-8096-8721a1887aad',...",{'ended': None},NaN,...,0,0,0,0,0,0,0,0,0,0
69660,6b94062e-78a3-46e8-b861-d801dfe27376,Studio,05fa6a09-ff92-3d34-bdbb-5141d3c24f38,100,Studio Toupie,NaN,NaN,NaN,{'ended': None},NaN,...,0,0,0,0,0,0,0,0,0,0
69661,f7362574-05ac-4c21-8196-26a09d6e5fe7,Studio,05fa6a09-ff92-3d34-bdbb-5141d3c24f38,100,FatCat Studio,NaN,NaN,NaN,{'ended': None},NaN,...,0,0,0,0,0,0,0,0,0,0
69662,6bd7adb1-b8dd-4ee5-bbe8-788444556350,Studio,05fa6a09-ff92-3d34-bdbb-5141d3c24f38,100,Farida Studio,"FARIDA STUDIO, Lintel 17, 27711 Osterholz-Scha...",NaN,"{'id': '9c607066-ceb6-4a78-a614-4c14a2b3ec35',...",{'ended': None},"recording studio located near Bremen, Germany",...,0,0,0,0,0,0,0,0,0,0

In [14]:
merged_df = merged_df.rename(columns={"arranged at_x": "arranged at_recording", "arranged at_y": "arranged at_work"})

In [19]:
merged_df['recorded at'].value_counts()

recorded at
0    58003
1    11660
Name: count, dtype: int64

In [20]:
merged_df.to_csv('Merged Dataset.csv')